# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/5450e970-b913-4e38-8783-2358111e5ef4";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-ffec9d7a-c16e-47ac-98e4-e83bf91d7d43".device = "/dev/disk/by-uuid/ffec9d7a-c16e-47ac-98e4-e83bf91d7d43";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/FA4D-EE78";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/var/lib/docker/overlay2/720c5358aa4948965f82b61b9e8c2bd1753147e96fe10287956f0f9f7f6c8044/merged" =
    { device = "overlay";
      fsType = "overlay";
    };

  fileSystems."/var/lib/docker/overlay2/66efdfe15f8b101c59bdb016fbee7ee40ba3b48d0773981a23d7e6c873217399/merged" =
    { device = "overlay";
      fsType = "overlay";
    };

  fileSystems."/var/lib/docker/overlay2/847a5fd6d8c3bf1b22b4d422bd6cd7a151691c36c8c2ad65a9c876b2d9364f95/merged" =
    { device = "overlay";
      fsType = "overlay";
    };

  fileSystems."/var/lib/docker/overlay2/034449852ebd384998690b59970b5f811a1959295d2d63341be3113b203eb557/merged" =
    { device = "overlay";
      fsType = "overlay";
    };

  fileSystems."/var/lib/docker/overlay2/792ae60985d6447a9af7dea20f7e6332ebb822f6f35ed5eed04fa1a8ba6700ac/merged" =
    { device = "overlay";
      fsType = "overlay";
    };

  fileSystems."/var/lib/docker/overlay2/921ddc3f621d7ffeed9f67b143a865aa8e3a462979e09f9bad68952802699ed1/merged" =
    { device = "overlay";
      fsType = "overlay";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/77fa1870-8fc7-4bf3-aeb7-dc6be86f2bff"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-32f4fa6382dc.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-3df5c750918e.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-e36f91a89be0.useDHCP = lib.mkDefault true;
  # networking.interfaces.docker0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.tailscale0.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth62a3073.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth7eb5f26.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethf6c8e8d.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
